services:
  app1:
    build:
      context: ./app
    container_name: backend-app-1
    expose:
      - "5000"
    environment:
      APP_NAME: "APP_ONE"
    networks:
      - app_net

  app2:
    build:
      context: ./app
    container_name: backend-app-2
    expose:
      - "5000"
    environment:
      APP_NAME: "APP_TWO"
    networks:
      - app_net

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - app1
      - app2
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
