name: Policy as Code (OPA / Conftest)

on:
  push:
  pull_request:

jobs:
  policy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_0.50.0_Linux_x86_64.tar.gz \
            | tar xz
          sudo mv conftest /usr/local/bin/

      - name: Run Dockerfile policies
        run: |
          conftest test app/Dockerfile \
            --policy policy/docker

          conftest test nginx/Dockerfile \
            --policy policy/docker
