name: Trivy - Image

on:
  push:
    branches: [ "**" ]
  pull_request:

env:
  IMAGE_NAME: devsecops-app:${{ github.sha }}

jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker CLI (already present on ubuntu-latest)
        run: docker version

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME -f app/Dockerfile app/

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share-keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy Image scan
        run: |
          trivy image \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            $IMAGE_NAME
