name: Trivy - Image

on:
  push:
    branches: [ "**" ]
  pull_request:

env:
  IMAGE_NAME: devsecops-app:${{ github.sha }}

jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker CLI (already present on ubuntu-latest)
        run: docker version

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME -f app/Dockerfile app/

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
           | sudo sh -s -- -b /usr/local/bin


      - name: Run Trivy Image scan
        run: |
          trivy image \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            $IMAGE_NAME
